### ISSUE TITLE
Any chances to port it to Erlang or how to go about it?

### ISSUE THREAD

**Issue by akamanocha** [Financial-Times/tapper#17]
Hi,

Would like to see if the same can be ported to Erlang? 

Currently there does not exist any instrumentation library for Erlang in Zipkin. There exist one for Opentracing: https://github.com/Bluehouse-Technology/otter
and Opencensus:  https://github.com/census-instrumentation/opencensus-erlang
(but not zipkin, again)

Also quoting from Adrian Cole form zipkin gitter:

> @akamanocha I would raise an issue in https://github.com/Financial-Times/tapper to ask to extract the erlang library. this will save you time, if they accept

I am saying if this can be done, how easy or difficult it would be? And where to start, may be I can help...

**Comment by ellispritchard** [comment]
Hi; there is no Erlang library underlying Tapper to extract: it's 100% written in Elixir.

If you can compile the Elixir code as part of your build, it produces BEAM files that you can call from Erlang, but you would need to bring along all the Elixir library modules as well, which may not be acceptable to you.

Why can you not use the opencensus-erlang project, with a Zipkin back end?

**Comment by akamanocha** [comment]
sure thanks. 

I will have to look into opencensus / opnetracing then. There is lots of confusion in the same. But if that is the way you suggest, I think I should look.

**Comment by akamanocha** [comment]
Thanks for the help. Closing it (the issue) for the time.
