### ISSUE TITLE
Integer value for binary annotations incompatible with many zipkin collectors

### ISSUE THREAD

**Issue by chad-g-adams** [Financial-Times/tapper#19]
Generating a trace with Tapper is resulting in a json payload that has binary annotations with a `value` field having integer value (example: http.status_code). See a full example from Tapper here:
https://gist.github.com/chad-g-adams/213aaeca0a9912b7adaf5314ed999038

Sending such a trace to zipkin collectors is giving issues:

* Zipkin UI ignores all integer annotations (simply not showing any of them in the UI)
* Jaeger UI is showing large random negative numbers instead of the proper http status code
* Honeycomb's opentracing proxy is reporting errors: `error="json: cannot unmarshal number into Go struct field binaryAnnotation.value of type string"`

More details copied from the gitter chat room:

* According to this zipkin v1 API documentation, binary annotation's value field must be a string:
https://github.com/apache/incubator-zipkin-api/blob/master/zipkin-api.yaml
* when zipkin handles the json the annotation value is expected to be boolean or string (not integer): https://github.com/apache/incubator-zipkin/blob/master/zipkin/src/main/java/zipkin2/internal/V1JsonSpanReader.java#L148...L154
* when honeycomb proxy handles the annotation it's expected to be string: https://github.com/honeycombio/honeycomb-opentracing-proxy/blob/36b46198efb278a7fc6c6879bf37631fc1f60ebd/types/json.go#L95

Could it mean Tapper is not fully compatible with the zipkin v1 API?

**Comment by adriancole** [comment]
zipkin hasn't supported numeric binary annotations in a meaningful way
since inception. the myriad of types were an accident of promoting all
thrift value types and a historical motivator for the v2 format which
doesnt do that.

a zipkin library shouldn't emit numeric binary annotations as they will be
dropped.

**Comment by ellispritchard** [comment]
Oh, how interesting! It's very surprising that this has not been spotted before. Will fix.

**Comment by ellispritchard** [comment]
> the myriad of types were an accident of promoting all thrift value types and a historical motivator for the v2 format which doesnt do that.

@adriancole Tapper is producing a `type` field for anything that isn't a string or boolean, but according to the reference implementation linked above, this is never processed. 

I presume I picked this up from some other (earlier) spec, so do you know if it is it safe to drop all the `type` properties in v1 and make the encoding simpler?

**Comment by adriancole** [comment]
what we do is use boolean only for the special case of remote address "sa"
"ca" "ma" annotation and stringify the rest. effectively boolean becomes an
internal hack to associate a remote IP and everything else ends up the type
string. so user surface ends up with no real notion of type and type is
only used encoding in thrift.

**Comment by ellispritchard** [comment]
Hmm, OK. I think I'll leave `type` in, release the fix (everything's a string except booleans), and actually implement the v2 format so I can stop pondering about the vagaries of v1... :)

Thanks for picking up on this.

**Comment by adriancole** [comment]
heh good choice
