### ISSUE TITLE
Add to zipkin instrumentations list?

### ISSUE THREAD

**Issue by adriancole** [Financial-Times/tapper#2]
Hi, we have a list to help users discover things. If interested, please add tapper here https://github.com/openzipkin/openzipkin.github.io/blob/master/_data/community_instrumentations.yml

**Comment by ellispritchard** [comment]
Cheers Adrian; will do once I've released the `Plug` integration.

**Comment by adriancole** [comment]
ps would you be up to sharing something about your tracing site? we're having a workshop next month and would be grand if you can come or attend remote. don't have your email, so can't add you to the doc, but you can gitter me or add yourself https://docs.google.com/document/d/12erSNS8gUIH6t2x4Om-HC4wUH20RrfyxMN2dJ0ILf6U/edit#

**Comment by ellispritchard** [comment]
Oooh, interesting; I expect @mclarke47 and I will hop on the remote.

**Comment by adriancole** [comment]
sweet. there's a slot at 9:30 or 10:00 with your name on it if you don't
mind sharing what you're up to! you can dive right in and not be formal as
everyone are experienced

**Comment by ellispritchard** [comment]
Pull request to community instrumentations accepted, merged.
