### ISSUE TITLE
Foundation Observability Working Group

### ISSUE THREAD

**Issue by tsloughter** [Financial-Times/tapper#21]
Hi, I wanted to see if you had interest in taking part in the work we are doing in the Erlang Foundation's [Observability working group](https://erlef.org/observability-wg/), https://github.com/erlef/eef-observability-wg/.

For tracers like Tapper in particular checkout OpenCensus (https://github.com/census-instrumentation/opencensus-erlang) -- being merged with OpenTracing and renamed OpenTelemetry (https://opentelemetry.io/). We've been working with the Spandex (https://github.com/spandex-project) team to consolidate the community on one underlying tracer library. See https://github.com/opencensus-beam/ for existing instrumentation.

For events, whether for metrics or traces, we are focusing on https://github.com/beam-telemetry

**Comment by ellispritchard** [comment]
Hi Tristan; thanks for the invite, that all looks very exciting!

Unfortunately I'm not doing enough production Erlang/Elixir at the moment to keep up on this stuff, nor do I have enough spare time to get stuck in to anything new, so I feel that my contributions would be rather limited. 

I'm sorry but I'll have to decline.

Good luck with your efforts!

**Comment by tsloughter** [comment]
Ok, understandable. Do you intend to keep active development on Tapper or just bug fixes? Our hope was to consolidate effort, like we are with spandex, so even if you aren't able to join our efforts it would be great if you could mention them in the Tapper readme.

**Comment by ellispritchard** [comment]
I'm going to be maintaining Tapper so long as I believe there is demand; the principle purpose for its being is for Zipkin server support, not multi-backend tracing/stats like OpenCensus, so I won't be adding new back-ends, though people are free to write their own (I did have a conversation recently about making the trace-ids compatible with DataDog, but that's as far as I'd go).

Is the idea that existing frameworks e.g. Spandex, adopt the OpenTelemetry interface, or become a implementation for beam-telemetry? Any idea how beam-telemetry/eef-observabilty relates to the OpenTelemetry interface spec?

**Comment by tsloughter** [comment]
The idea is to only have one implementation, unless a need arises that can not be met in a single implementation. So Spandex is being sunset.

Though most important is to share how context is propagated and the format of span id, trace id and trace options. Otherwise applications that have span creation from different libraries won't work together.

A number of us in the working group were already working on the OpenTelemetry spec.
