### ISSUE TITLE
Log clutter

### ISSUE THREAD

**Issue by TKasekamp** [Financial-Times/tapper#7]
Tapper logs when it starts and finishes a log, for example here https://github.com/Financial-Times/tapper/blob/master/lib/tapper/tracer/server.ex#L67

These logs create a lot of noise when in production env. Could there be a config to turn off these logs?

**Comment by ellispritchard** [comment]
Yes, it is a bit noisy: this kind of thing needs to either be debug, or we need some kind of shim between `Logger` and tapper log calls where we can add some more fine-grained control.

**Comment by ellispritchard** [comment]
cf. the logging shim in [CORSICA](https://github.com/whatyouhide/corsica/blob/master/lib/corsica.ex)

**Comment by ellispritchard** [comment]
Fixed in 0.3.3.
