### ISSUE TITLE
"unknown" is being sent as serviceName

### ISSUE THREAD

**Issue by ellispritchard** [Financial-Times/tapper#9]
According to the [Thrift](https://github.com/openzipkin/zipkin-api/blob/master/thrift/zipkinCore.thrift) documentation, "unknown" should be sent when you don't know the service name, of, say an incoming trace, leaving it to be filled in using data from the originating service. Now we're using istio, we can see that this is incorrect behaviour (at least for the JSON format), since you end up with "unknown" as the service name, rather than the upstream name. Java Brave seems to handle this correctly. In the [v2 JSON API](https://github.com/openzipkin/zipkin-api/blob/682de48c7e1161f59d4e1ecfae0d631eea85ea44/zipkin2-api.yaml), this field is specifically marked as being able to be omitted:

```
 Endpoint:
    type: object
    title: Endpoint
    description: The network context of a node in the service graph
    properties:
      serviceName:
        type: string
        description: |
                    Lower-case label of this node in the service graph, such as "favstar". Leave
                    absent if unknown.
                  
                    This is a primary label for trace lookup and aggregation, so it should be
                    intuitive and consistent. Many use a name from service discovery.
```

**Comment by adriancole** [comment]
Yep, in v2 you can leave out the field completely. in v1 you can set it to
empty string for the same effect.
